import { MenuProduct } from "@/types/Product";

const EMPTY: MenuProduct[] = [];

const SMALL: MenuProduct[] = [
  {
    id: "1",
    imageSource: "/assets/burger1.png",
    title: "Burger 1",
    price: 5.297,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "2",
    imageSource: "/assets/burger2.png",
    title: "Burger 2",
    price: 7.556,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
];

const MEDIUM: MenuProduct[] = [
  {
    id: "1",
    imageSource: "/assets/burger-bacon-egg.png",
    title: "Burger Smoke BBQ",
    price: 5.598,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "2",
    imageSource: "/assets/burger-vegan.png",
    title: "Vegan Burger",
    price: 5.4985,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "3",
    imageSource: "/assets/burger3.png",
    title: "Burger poulet",
    price: 5.367,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "4",
    imageSource: "/assets/drink1.png",
    title: "Coke 25cl",
    price: 3.568,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "5",
    imageSource: "/assets/drink2.png",
    title: "Pepsi 25cl",
    price: 3.487,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
];

const LARGE: MenuProduct[] = [
  {
    id: "1",
    imageSource: "/assets/bowl1.png",
    title: "Sashimi Fusion Bowl",
    price: 13.5,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },

  {
    id: "2",
    imageSource: "/assets/bowl5.png",
    title: "Potatoe Salad",
    price: 9.5,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "3",
    imageSource: "/assets/bowl4.png",
    title: "Salmon Bowl",
    price: 14.501,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "4",
    imageSource: "/assets/bowl2.png",
    title: "Avocado Feast",
    price: 11.495,
    quantity: 0,
    isAvailable: true,
    isAdvertised: true,
  },

  {
    id: "5",
    imageSource: "/assets/bowl3.png",
    title: "Chicken Salad",
    price: 12.5,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "6",
    imageSource: "/assets/sweet-fries.png",
    title: "Sweet Plate",
    price: 7.5,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "7",
    imageSource: "/assets/burger-vegan.png",
    title: "Burger Vegan",
    price: 8.5,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "8",
    imageSource: "/assets/sweet-fries-bucket.png",
    title: "Sweet Bucket",
    price: 4,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "9",
    imageSource: "/assets/drink5.png",
    title: "Rainbow Smoothie",
    price: 8.5,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "10",
    imageSource: "/assets/drink4.png",
    title: "Bubble Tea Vanilla",
    price: 3.9,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "11",
    imageSource: "/assets/drink6.jpg",
    title: "Oasis Pomme Cassis Framboise",
    price: 2.5,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "12",
    imageSource: "/assets/ice-cream.png",
    title: "Glaces artisanales",
    price: 2.9,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
];

export const fakeMenu = {
  EMPTY,
  SMALL,
  MEDIUM,
  LARGE,
};
